[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_SVR_API = "https://yamovie-server-staging.herokuapp.com/api"
  REACT_APP_SVR_AUTH = "https://yamovie-server-staging.herokuapp.com/auth"
  REACT_APP_SVR_USERS = "https://yamovie-server-staging.herokuapp.com/users"
  REACT_APP_SVR_PREFS = "https://yamovie-server-staging.herokuapp.com/preferences"

[context.branch-deploy.environment]
  REACT_APP_SVR_API = "https://yamovie-server-staging.herokuapp.com/api"
  REACT_APP_SVR_AUTH = "https://yamovie-server-staging.herokuapp.com/auth"
  REACT_APP_SVR_USERS = "https://yamovie-server-staging.herokuapp.com/users"
  REACT_APP_SVR_PREFS = "https://yamovie-server-staging.herokuapp.com/preferences"
