[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.deploy-staging]
  REACT_APP_SVR_API = "https://yamovie-server-staging.herokuapp.com/api"
  REACT_APP_SVR_AUTH = "https://yamovie-server-staging.herokuapp.com/auth"
  REACT_APP_SVR_USERS = "https://yamovie-server-staging.herokuapp.com/users"
